//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even valued terms.
//Fibonacci is generated by adding the previous two terms


var sequence = [1,2];
while (sequence[sequence.length - 2] + sequence[sequence.length - 1] < 4000000) {
    var newFib = sequence[sequence.length - 2] + sequence[sequence.length - 1];
    sequence.push(newFib);
}

var evenSum = 0;
sequence.map(function(e) {
    if (e % 2 === 0) { evenSum += e; }
});
console.log(sequence);
console.log(evenSum);

